apiVersion: v1
kind: Namespace
metadata:
  name: background-jobs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: background-jobs
  namespace: background-jobs
---
apiVersion: v1
kind: Service
metadata:
  name: background-jobs
  namespace: background-jobs
spec:
  type: NodePort
  selector:
    app: background-jobs
    version: v0.1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-jobs
  namespace: background-jobs
  labels:
    app: background-jobs
    version: v0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: background-jobs
      version: v0.1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
      labels:
        app: background-jobs
        version: v0.1
    spec:
      containers:
      - name: background-jobs
        image: xeviknal/background-jobs:v0.1
        imagePullPolicy: IfNotPresent
      serviceAccountName: background-jobs
